/**
 * Jeu d’emojis « de base » iOS, avec tags EN/FR pour la recherche.
 * Les séquences ZWJ sont volontairement exclues.
 */

const list = (str) => str.trim().split(/\s+/);

export const EMOJI_GROUPS = [
  {
    name: "Favoris",
    emojis: list("💖 ⭐ ✨ 🌈 🦄 🐱 🐶 🐰 🐻 🌸 🌻 🦋 🍦 🎂 🎈 📷 👑 😘 😂 😎 🔥 🎵 🌙 ☁️ 🍓 🍩 🎀 🐣 🐯 🍀 💜 💞 🧁 🍉 🍒 💗"),
  },
  {
    name: "Smileys",
    emojis: list("😀 😃 😄 😁 😆 😅 🤣 😂 🙂 🙃 😉 😊 😇 🥰 😍 🤩 😘 😗 😚 😙 🥲 😋 😛 😜 🤪 😝 🤑 🤗 🤭 🤫 🤔 🤐 🤨 😐 😑 😶 😏 😒 🙄 😬 🤥 😌 😔 😪 🤤 😴 😷 🤒 🤕 🤢 🤮 🤧 🥵 🥶 🥴 😵 🤯 🤠 🥳 🥸 😎 🤓 🧐 😕 😟 🙁 ☹️ 😮 😯 😲 😳 🥺 😦 😧 😨 😰 😥 😢 😭 😱 😖 😣 😞 😓 😩 😫 🥱 😤 😡 😠 🤬 😈 👿 💀 ☠️ 💩 🤡 👹 👺 👻 👽 👾 🤖 😺 😸 😹 😻 😼 😽 🙀 😿 😾"),
  },
  {
    name: "Gestes",
    emojis: list("👋 🤚 🖐️ ✋ 🖖 👌 🤌 🤏 ✌️ 🤞 🤟 🤘 🤙 👈 👉 👆 👇 ☝️ 👍 👎 ✊ 👊 🤛 🤜 👏 🙌 👐 🤲 🤝 🙏 ✍️ 💅 🤳 💪 🦵 🦶 👂 👃 🧠 🦷 👀 👁️ 👅 👄 💋"),
  },
  {
    name: "Animaux",
    emojis: list("🐶 🐱 🐭 🐹 🐰 🦊 🐻 🐼 🐨 🐯 🦁 🐮 🐷 🐽 🐸 🐵 🙈 🙉 🙊 🐒 🐔 🐧 🐦 🐤 🐣 🐥 🦆 🦅 🦉 🦇 🐺 🐗 🐴 🦄 🐝 🐛 🦋 🐌 🐞 🐜 🦗 🕷️ 🕸️ 🦂 🐢 🐍 🦎 🦖 🦕 🐙 🦑 🦐 🦞 🦀 🐡 🐠 🐟 🐬 🐳 🐋 🦈 🐊 🐅 🐆 🦓 🦍 🐘 🦛 🦏 🐪 🐫 🦒 🦘 🐄 🐎 🐖 🐑 🦙 🐐 🦌 🐕 🐩 🐈 🐓 🦃 🦚 🦜 🦢 🕊️ 🐇 🦝 🦡 🦦 🦥 🐁 🐀 🐿️ 🦔 🐾 🐉 🦠"),
  },
  {
    name: "Nature",
    emojis: list("🌵 🎄 🌲 🌳 🌴 🌱 🌿 ☘️ 🍀 🎍 🎋 🍃 🍂 🍁 🍄 🌾 💐 🌷 🌹 🥀 🌺 🌸 🌼 🌻 🌞 🌝 🌛 🌜 🌚 🌕 🌖 🌗 🌘 🌑 🌒 🌓 🌔 🌙 🌎 🌍 🌏 💫 ⭐ 🌟 ✨ ⚡ ☄️ 💥 🔥 🌪️ 🌈 ☀️ 🌤️ ⛅ ☁️ 🌦️ 🌧️ ⛈️ 🌨️ ❄️ ☃️ ⛄ 💨 💧 💦 ☔ ☂️ 🌊 🌫️ 🐚"),
  },
  {
    name: "Gourmand",
    emojis: list("🍏 🍎 🍐 🍊 🍋 🍌 🍉 🍇 🍓 🫐 🍈 🍒 🍑 🥭 🍍 🥥 🥝 🍅 🍆 🥑 🥦 🥬 🥒 🌶️ 🌽 🥕 🧄 🧅 🥔 🍠 🥐 🥯 🍞 🥖 🥨 🧀 🥚 🍳 🥞 🧇 🥓 🍔 🍟 🍕 🌭 🥪 🌮 🌯 🥗 🥘 🍝 🍜 🍲 🍛 🍣 🍱 🥟 🍤 🍙 🍚 🍥 🥠 🍢 🍡 🍧 🍨 🍦 🥧 🧁 🍰 🎂 🍮 🍭 🍬 🍫 🍿 🍩 🍪 🌰 🥜 🍯 🥛 🍼 ☕ 🍵 🧃 🥤 🧊 🍽️ 🥄"),
  },
  {
    name: "Activités",
    emojis: list("⚽ 🏀 🏈 ⚾ 🥎 🎾 🏐 🏉 🥏 🎱 🪀 🏓 🏸 🏒 🏑 🥍 🏏 🥅 ⛳ 🪁 🎣 🤿 🎽 🎿 🛷 🥌 🎯 🪃 🎮 🕹️ 🎰 🎲 🧩 🎨 🎭 🎪 🎟️ 🎫 🎖️ 🏆 🏅 🥇 🥈 🥉 🎗️ 🎼 🎵 🎶 🎤 🎧 📻 🎷 🪗 🎸 🎹 🎺 🎻 🪕 🥁 🎬 🎈 🎉 🎊 🎁 🎀 🎃 🧨 🪅"),
  },
  {
    name: "Voyages",
    emojis: list("🚗 🚕 🚙 🚌 🚎 🏎️ 🚓 🚑 🚒 🚐 🚚 🚛 🚜 🛴 🚲 🛵 🏍️ 🚨 🚡 🚠 🚃 🚋 🚞 🚝 🚄 🚅 🚈 🚂 🚆 🚇 🚊 🚉 ✈️ 🛫 🛬 🛩️ 💺 🚀 🛸 🚁 🛶 ⛵ 🚤 🛥️ 🛳️ ⛴️ 🚢 ⚓ ⛽ 🚧 🗺️ 🗿 🗽 🗼 🏰 🏯 🎡 🎢 🎠 ⛲ ⛱️ 🏖️ 🏝️ 🏜️ 🌋 ⛰️ 🏔️ 🗻 🏕️ ⛺ 🏠 🏡 🏘️ 🏗️ 🏭 🏢 🏬 🏥 🏦 🏨 🏪 🏫 💒 🏛️ ⛪ 🕌 🕍 🛕 ⛩️ 🌁 🌃 🏙️ 🌄 🌅 🌆 🌇 🌉 🎆 🎇 🌌 🗾"),
  },
  {
    name: "Objets",
    emojis: list("⌚ 📱 💻 ⌨️ 🖥️ 🖨️ 🖱️ 💽 💾 💿 📀 📷 📸 📹 🎥 📽️ 📞 ☎️ 📟 📠 📺 📼 🔍 🔎 🕯️ 💡 🔦 🏮 📔 📕 📖 📗 📘 📙 📚 📓 📒 📜 📄 📰 🔖 🏷️ 💰 💵 💳 ✉️ 📧 📩 📤 📥 📦 📫 📮 ✏️ ✒️ 🖋️ 🖊️ 🖌️ 🖍️ 📝 💼 📁 📂 📅 📆 📈 📉 📊 📋 📌 📍 📎 📏 📐 ✂️ 🔒 🔓 🔑 🗝️ 🔨 🔧 🔩 ⚙️ 🧲 🔗 ⛓️ 🧪 🧫 🧬 🔬 🔭 📡 💉 💊 🩹 🩺 🚪 🪑 🚿 🛁 🧴 🧷 🧹 🧺 🧻 🧼 🧽 🛒 🪥 🧸 🕶️ 👓 👕 👗 👚 👖 🧣 🧤 🧥 🧦 👛 👜 🎒 👑 💎 👞 👟 🩰 👠 🥾 🧢 🎩 🎓"),
  },
  {
    name: "Symboles",
    emojis: list("❤️ 🧡 💛 💚 💙 💜 🖤 🤍 🤎 💔 ❣️ 💕 💞 💓 💗 💖 💘 💝 💟 ♈ ♉ ♊ ♋ ♌ ♍ ♎ ♏ ♐ ♑ ♒ ♓ ✔️ ✅ ❌ ❎ ➕ ➖ ➗ ✖️ ♾️ ‼️ ⁉️ ❓ ❔ ❕ ❗ 〰️ 💯 ⚠️ 🚫 ⛔ ♻️ 🔱 🔰 ⚜️ 🔆 🔅 ✳️ ❇️ 🌐 ⬆️ ↗️ ➡️ ↘️ ⬇️ ↙️ ⬅️ ↖️ ↕️ ↔️ ↩️ ↪️ 🔃 🔄 🔔 🚩 🏁 🎌 🔴 🟠 🟡 🟢 🔵 🟣 🟤 ⚫ ⚪ 🟥 🟧 🟨 🟩 🟦 🟪 ⬛ ⬜ 🔶 🔷 🔸 🔹 🔺 🔻 💠 🔘"),
  },
];

/** @type {Record<string, string>} tags EN + FR, espaces séparés */
export const EMOJI_TAGS = {
  "💖": "sparkling heart coeur scintillant love amour pink rose",
  "⭐": "star etoile yellow jaune",
  "✨": "sparkles etincelles glitter brillant magic magie",
  "🌈": "rainbow arc-en-ciel colors couleurs weather meteo",
  "🦄": "unicorn licorne horse cheval fantasy magie magic",
  "🐱": "cat chat kitten chaton animal pet",
  "🐶": "dog chien puppy chiot animal pet",
  "🐰": "rabbit lapin bunny animal",
  "🐻": "bear ours animal",
  "🌸": "cherry blossom fleur de cerisier flower fleur spring printemps pink rose",
  "🌻": "sunflower tournesol flower fleur yellow jaune",
  "🦋": "butterfly papillon insect insecte",
  "🍦": "soft ice cream glace soft dessert food nourriture",
  "🎂": "birthday cake gateau anniversaire dessert food nourriture party fete",
  "🎈": "balloon ballon party fete celebration",
  "📷": "camera appareil photo photography photo",
  "👑": "crown couronne king roi queen reine royal",
  "😘": "face blowing a kiss bisous kiss bisou love amour smile sourire",
  "😂": "face with tears of joy rire larmes joy joie laugh laughing smile sourire lol",
  "😎": "smiling face with sunglasses lunettes cool smile sourire",
  "🔥": "fire feu flame flamme hot chaud lit",
  "🎵": "musical note note musique music song chanson",
  "🌙": "crescent moon lune croissant night nuit",
  "☁️": "cloud nuage weather meteo sky ciel",
  "🍓": "strawberry fraise fruit food nourriture berry baie",
  "🍩": "doughnut donut beignet dessert food nourriture sweet sucre",
  "🎀": "ribbon noeud ruban bow pink rose gift cadeau",
  "🐣": "hatching chick poussin eclosion bird oiseau baby bebe",
  "🐯": "tiger face tigre animal",
  "🍀": "four leaf clover trefle quatre feuilles luck chance irish",
  "💜": "purple heart coeur violet love amour",
  "💞": "revolving hearts coeurs tournants love amour",
  "🧁": "cupcake muffin dessert food nourriture sweet sucre",
  "🍉": "watermelon pasteque fruit food nourriture",
  "🍒": "cherries cerises fruit food nourriture",
  "💗": "growing heart coeur grandissant love amour pink rose",
  "😀": "grinning face visage souriant smile sourire happy heureux",
  "😃": "grinning face with big eyes grands yeux smile sourire happy heureux",
  "😄": "grinning face with smiling eyes yeux souriants smile sourire happy heureux laugh rire",
  "😁": "beaming face with smiling eyes rayonnant smile sourire happy heureux",
  "😆": "grinning squinting face yeux plisses laugh rire smile sourire",
  "😅": "grinning face with sweat sueur nervous nerveux smile sourire awkward",
  "🤣": "rolling on the floor laughing mort de rire rofl lol smile sourire",
  "🙂": "slightly smiling face legerement souriant smile sourire",
  "🙃": "upside-down face tete a lenvers silly idiot smile sourire",
  "😉": "winking face clin doeil wink flirt smile sourire",
  "😊": "smiling face with smiling eyes blush rougeur smile sourire happy heureux",
  "😇": "smiling face with halo ange angel innocent smile sourire",
  "🥰": "smiling face with hearts coeurs love amour adore smile sourire crush",
  "😍": "smiling face with heart-eyes yeux en coeur love amour crush smile sourire",
  "🤩": "star-struck etoiles dans les yeux wow star etoile smile sourire",
  "😗": "kissing face bisou kiss smile sourire",
  "😚": "kissing face with closed eyes yeux fermes bisou kiss smile sourire",
  "😙": "kissing face with smiling eyes bisou kiss smile sourire",
  "🥲": "smiling face with tear larme touchant smile sourire bittersweet",
  "😋": "face savoring food miom yum delicious delicieux smile sourire",
  "😛": "face with tongue langue silly idiot smile sourire",
  "😜": "winking face with tongue clin doeil langue silly smile sourire",
  "🤪": "zany face fou crazy silly idiot smile sourire",
  "😝": "squinting face with tongue langue yeux plisses silly smile sourire",
  "🤑": "money-mouth face argent money rich riche dollar",
  "🤗": "hugging face calin hug câlin smile sourire",
  "🤭": "face with hand over mouth oops oups giggle ricaner",
  "🤫": "shushing face chut quiet silence secret",
  "🤔": "thinking face reflechir pensee hmm think",
  "🤐": "zipper-mouth face zip secret quiet silence",
  "🤨": "face with raised eyebrow sourcil leve skeptical sceptique suspicion",
  "😐": "neutral face neutre meh blank",
  "😑": "expressionless face sans expression meh blank",
  "😶": "face without mouth sans bouche quiet silence mute muet",
  "😏": "smirking face sourire en coin smirk flirty",
  "😒": "unamused face pas amuse annoyed agace meh",
  "🙄": "face with rolling eyes yeux au ciel annoyed agace whatever",
  "😬": "grimacing face grimace awkward gene nervous",
  "🤥": "lying face mensonge pinocchio lie",
  "😌": "relieved face soulage calm calme peace paix",
  "😔": "pensive face pensif sad triste down",
  "😪": "sleepy face somnolent tired fatigue sleep dormir",
  "🤤": "drooling face bave yum delicious delicieux",
  "😴": "sleeping face dort sleep dormir zzz tired fatigue",
  "😷": "face with medical mask masque sick malade doctor medecin covid",
  "🤒": "face with thermometer thermometre fever fievre sick malade",
  "🤕": "face with head-bandage bandage blessure hurt blesse injured",
  "🤢": "nauseated face nausee sick malade green vert",
  "🤮": "face vomiting vomir sick malade puke",
  "🤧": "sneezing face eternuement sneeze cold rhume sick malade",
  "🥵": "hot face chaud heat chaleur sweating sueur",
  "🥶": "cold face froid freezing gele ice glace blue bleu",
  "🥴": "woozy face etourdi drunk tipsy dizzy",
  "😵": "dizzy face etourdi knocked out knocked",
  "🤯": "exploding head tete qui explose mind blown wow shock choc",
  "🤠": "cowboy hat face cowboy western",
  "🥳": "partying face fete party celebration birthday anniversaire",
  "🥸": "disguised face deguise disguise glasses lunettes nose nez",
  "🤓": "nerd face intello geek glasses lunettes",
  "🧐": "face with monocle monocle fancy chic inspect",
  "😕": "confused face confus confused puzzled",
  "😟": "worried face inquiet worried anxious",
  "🙁": "slightly frowning face triste sad frown",
  "☹️": "frowning face triste sad frown",
  "😮": "face with open mouth bouche ouverte surprise wow omg",
  "😯": "hushed face surpris surprise wow",
  "😲": "astonished face etonne shock choc surprise wow",
  "😳": "flushed face rougissant embarrassed gene blush",
  "🥺": "pleading face yeux de chiot puppy eyes please sil te plait cute mignon",
  "😦": "frowning face with open mouth inquiet worried",
  "😧": "anguished face angoisse anguish worry",
  "😨": "fearful face peur fear scared effraye",
  "😰": "anxious face with sweat anxieux nervous sueur worry",
  "😥": "sad but relieved face triste soulage sad",
  "😢": "crying face pleure cry sad triste tear larme",
  "😭": "loudly crying face pleure fort sob cry sad triste",
  "😱": "face screaming in fear cri peur scream scared horror horreur",
  "😖": "confounded face contrarie frustrated",
  "😣": "persevering face perseverance struggle effort",
  "😞": "disappointed face decu disappointed sad triste",
  "😓": "downcast face with sweat sueur tired fatigue sad",
  "😩": "weary face fatigue exhausted weary tired",
  "😫": "tired face fatigue tired exhausted",
  "🥱": "yawning face baille yawn sleepy tired fatigue",
  "😤": "face with steam from nose fume angry colere triumph",
  "😡": "pouting face rage angry colere mad red rouge",
  "😠": "angry face en colere angry mad",
  "🤬": "face with symbols on mouth insultes swearing angry colere",
  "😈": "smiling face with horns diable devil smile sourire evil mechant",
  "👿": "angry face with horns diable angry devil evil mechant",
  "💀": "skull crane death mort skeleton squelette",
  "☠️": "skull and crossbones tete de mort pirate death mort",
  "💩": "pile of poo caca poop funny drole",
  "🤡": "clown face clown circus cirque funny drole",
  "👹": "ogre oni demon japanese japonais monster monstre",
  "👺": "goblin tengu japanese japonais monster monstre",
  "👻": "ghost fantome halloween spooky spook",
  "👽": "alien extraterrestre ufo space espace",
  "👾": "alien monster monstre alien game jeu space",
  "🤖": "robot bot ai ia machine",
  "😺": "grinning cat chat souriant smile sourire cat",
  "😸": "grinning cat with smiling eyes chat joyeux smile sourire",
  "😹": "cat with tears of joy chat rire laugh smile sourire",
  "😻": "smiling cat with heart-eyes chat amoureux love amour",
  "😼": "cat with wry smile chat sourire en coin smirk",
  "😽": "kissing cat chat bisou kiss",
  "🙀": "weary cat chat surpris shock wow",
  "😿": "crying cat chat triste cry sad",
  "😾": "pouting cat chat fache angry colere",
  "👋": "waving hand salut hello hi bye au revoir wave main",
  "🤚": "raised back of hand dos de la main stop",
  "🖐️": "hand with fingers splayed main ouverte palm",
  "✋": "raised hand main levee stop high five",
  "🖖": "vulcan salute vulcan spock star trek",
  "👌": "ok hand ok parfait perfect",
  "🤌": "pinched fingers doigts pinces italian italien what quoi",
  "🤏": "pinching hand pincer small petit little",
  "✌️": "victory hand victoire peace paix v",
  "🤞": "crossed fingers doigts croises luck chance hope espoir",
  "🤟": "love-you gesture je taime asl love amour",
  "🤘": "sign of the horns rock metal cornes",
  "🤙": "call me hand appelle moi shaka hang loose",
  "👈": "backhand index pointing left gauche left point",
  "👉": "backhand index pointing right droite right point",
  "👆": "backhand index pointing up haut up point",
  "👇": "backhand index pointing down bas down point",
  "☝️": "index pointing up index haut up point",
  "👍": "thumbs up pouce like yes oui good bien ok",
  "👎": "thumbs down pouce bas dislike no non bad mauvais",
  "✊": "raised fist poing leve power solidarity",
  "👊": "oncoming fist coup de poing punch fist bump",
  "🤛": "left-facing fist poing gauche",
  "🤜": "right-facing fist poing droite",
  "👏": "clapping hands applaudissements clap bravo",
  "🙌": "raising hands hands up celebration yay hooray",
  "👐": "open hands mains ouvertes hug",
  "🤲": "palms up together paumes dua prayer",
  "🤝": "handshake poignee de main deal accord agreement",
  "🙏": "folded hands priere please sil te plait thank merci namaste high five",
  "✍️": "writing hand ecrire write pen stylo",
  "💅": "nail polish vernis ongles manicure sassy",
  "🤳": "selfie photo camera",
  "💪": "flexed biceps muscle fort strong gym sport",
  "🦵": "leg jambe kick",
  "🦶": "foot pied kick",
  "👂": "ear oreille hear entendre listen ecouter",
  "👃": "nose nez smell odeur",
  "🧠": "brain cerveau smart intelligent think pensee",
  "🦷": "tooth dent dentist dentiste smile sourire",
  "👀": "eyes yeux look regarder see voir peek",
  "👁️": "eye oeil look regarder see voir",
  "👅": "tongue langue taste gout lick",
  "👄": "mouth bouche lips levres kiss bisou",
  "💋": "kiss mark trace de rouge a levres bisou kiss love amour",
  "🐭": "mouse face souris animal",
  "🐹": "hamster animal pet cute mignon",
  "🦊": "fox renard animal",
  "🐼": "panda bear ours animal",
  "🐨": "koala animal australia australie",
  "🦁": "lion animal king roi",
  "🐮": "cow face vache animal farm ferme",
  "🐷": "pig face cochon animal farm ferme",
  "🐽": "pig nose groin cochon",
  "🐸": "frog grenouille animal",
  "🐵": "monkey face singe animal",
  "🙈": "see-no-evil monkey singe rien vu",
  "🙉": "hear-no-evil monkey singe rien entendu",
  "🙊": "speak-no-evil monkey singe rien dit",
  "🐒": "monkey singe animal",
  "🐔": "chicken poulet animal farm ferme bird oiseau",
  "🐧": "penguin pingouin animal bird oiseau cold froid",
  "🐦": "bird oiseau animal",
  "🐤": "baby chick poussin bebe bird oiseau",
  "🐥": "front-facing baby chick poussin bird oiseau",
  "🦆": "duck canard bird oiseau animal",
  "🦅": "eagle aigle bird oiseau animal",
  "🦉": "owl hibou chouette bird oiseau night nuit wise sage",
  "🦇": "bat chauve-souris halloween night nuit",
  "🐺": "wolf loup animal",
  "🐗": "boar sanglier animal",
  "🐴": "horse face cheval animal",
  "🐝": "honeybee abeille insect insecte honey miel",
  "🐛": "bug chenille insect insecte",
  "🐌": "snail escargot slow lent animal",
  "🐞": "lady beetle coccinelle insect insecte luck chance",
  "🐜": "ant fourmi insect insecte",
  "🦗": "cricket criquet insect insecte",
  "🕷️": "spider araignee insect insecte halloween",
  "🕸️": "spider web toile araignee halloween",
  "🦂": "scorpion animal",
  "🐢": "turtle tortue slow lent animal",
  "🐍": "snake serpent animal",
  "🦎": "lizard lezard reptile animal",
  "🦖": "t-rex tyrannosaure dinosaur dinosaure",
  "🦕": "sauropod dinosaure dinosaur",
  "🐙": "octopus poulpe pieuvre sea mer animal",
  "🦑": "squid calamar sea mer animal",
  "🦐": "shrimp crevette sea mer food nourriture",
  "🦞": "lobster homard sea mer food nourriture",
  "🦀": "crab crabe sea mer animal",
  "🐡": "blowfish poisson-globe fish poisson sea mer",
  "🐠": "tropical fish poisson tropical sea mer",
  "🐟": "fish poisson sea mer animal",
  "🐬": "dolphin dauphin sea mer animal",
  "🐳": "spouting whale baleine sea mer animal",
  "🐋": "whale baleine sea mer animal",
  "🦈": "shark requin sea mer animal",
  "🐊": "crocodile animal reptile",
  "🐅": "tiger tigre animal",
  "🐆": "leopard animal",
  "🦓": "zebra zebre animal",
  "🦍": "gorilla gorille animal ape",
  "🐘": "elephant animal",
  "🦛": "hippopotamus hippopotame animal",
  "🦏": "rhinoceros animal",
  "🐪": "camel chameau desert animal",
  "🐫": "two-hump camel dromadaire camel desert animal",
  "🦒": "giraffe girafe animal",
  "🦘": "kangaroo kangourou australia australie animal",
  "🐄": "cow vache animal farm ferme",
  "🐎": "horse cheval race animal",
  "🐖": "pig cochon animal farm ferme",
  "🐑": "ewe mouton sheep animal farm ferme",
  "🦙": "llama lama alpaca animal",
  "🐐": "goat chevre animal farm ferme",
  "🦌": "deer cerf animal",
  "🐕": "dog chien animal pet",
  "🐩": "poodle caniche dog chien",
  "🐈": "cat chat animal pet",
  "🐓": "rooster coq chicken animal farm ferme",
  "🦃": "turkey dinde thanksgiving animal bird oiseau",
  "🦚": "peacock paon bird oiseau",
  "🦜": "parrot perroquet bird oiseau",
  "🦢": "swan cygne bird oiseau",
  "🕊️": "dove colombe peace paix bird oiseau",
  "🐇": "rabbit lapin animal",
  "🦝": "raccoon raton laveur animal",
  "🦡": "badger blaireau animal",
  "🦦": "otter loutre animal",
  "🦥": "sloth paresseux slow lent animal",
  "🐁": "mouse souris animal",
  "🐀": "rat animal",
  "🐿️": "chipmunk ecureuil animal",
  "🦔": "hedgehog herisson animal",
  "🐾": "paw prints empreintes pattes animal pet",
  "🐉": "dragon fantasy animal myth",
  "🦠": "microbe virus bacteria bacterie germ germes science",
  "🌵": "cactus plant plante desert",
  "🎄": "christmas tree sapin noel christmas tree arbre",
  "🌲": "evergreen tree sapin arbre tree forest foret",
  "🌳": "deciduous tree arbre tree forest foret",
  "🌴": "palm tree palmier tree tropical beach plage",
  "🌱": "seedling pousse plant plante grow grandir",
  "🌿": "herb herbe leaf feuille plant plante",
  "☘️": "shamrock trefle irish luck chance",
  "🎍": "pine decoration decoration pin japanese japonais",
  "🎋": "tanabata tree arbre tanabata japanese japonais",
  "🍃": "leaf fluttering in wind feuille vent leaf",
  "🍂": "fallen leaf feuille morte autumn automne fall",
  "🍁": "maple leaf feuille derable autumn automne canada",
  "🍄": "mushroom champignon plant nature",
  "🌾": "sheaf of rice riz harvest recolte",
  "💐": "bouquet flowers fleurs gift cadeau",
  "🌷": "tulip tulipe flower fleur spring printemps",
  "🌹": "rose flower fleur love amour red rouge",
  "🥀": "wilted flower fleur fanee sad triste",
  "🌺": "hibiscus flower fleur tropical",
  "🌼": "blossom fleur flower yellow jaune",
  "🌞": "sun with face soleil smile sourire sun",
  "🌝": "full moon face pleine lune smile sourire",
  "🌛": "first quarter moon face premier quartier lune",
  "🌜": "last quarter moon face dernier quartier lune",
  "🌚": "new moon face nouvelle lune smile sourire",
  "🌕": "full moon pleine lune night nuit",
  "🌖": "waning gibbous moon lune gibbeuse",
  "🌗": "last quarter moon dernier quartier",
  "🌘": "waning crescent moon croissant decroissant",
  "🌑": "new moon nouvelle lune",
  "🌒": "waxing crescent moon croissant croissant",
  "🌓": "first quarter moon premier quartier",
  "🌔": "waxing gibbous moon lune gibbeuse croissante",
  "🌎": "globe americas terre earth world monde americas",
  "🌍": "globe europe africa terre earth world monde europe afrique",
  "🌏": "globe asia australia terre earth world monde asie",
  "💫": "dizzy etoile filante dizzy sparkle",
  "🌟": "glowing star etoile brillante star",
  "⚡": "high voltage eclair lightning orage electricity electricite",
  "☄️": "comet comete space espace",
  "💥": "collision explosion boom comic",
  "🌪️": "tornado twister storm tempete weather meteo",
  "☀️": "sun soleil weather meteo sunny ensoleille hot chaud",
  "🌤️": "sun behind small cloud soleil nuage weather meteo",
  "⛅": "sun behind cloud soleil derriere nuage weather meteo",
  "🌦️": "sun behind rain cloud soleil pluie weather meteo",
  "🌧️": "cloud with rain pluie rain weather meteo",
  "⛈️": "cloud with lightning and rain orage thunderstorm weather meteo",
  "🌨️": "cloud with snow neige snow weather meteo",
  "❄️": "snowflake flocon snow neige cold froid winter hiver",
  "☃️": "snowman bonhomme de neige snow neige winter hiver",
  "⛄": "snowman without snow bonhomme de neige snow neige",
  "💨": "dashing away vent wind dash fart pet",
  "💧": "droplet goutte water eau sweat sueur tear larme",
  "💦": "sweat droplets gouttes sweat sueur splash eau",
  "☔": "umbrella with rain drops parapluie pluie rain weather meteo",
  "☂️": "umbrella parapluie rain pluie",
  "🌊": "water wave vague ocean sea mer surf",
  "🌫️": "fog brouillard mist weather meteo",
  "🐚": "spiral shell coquillage shell beach plage sea mer",
  "🍏": "green apple pomme verte fruit food nourriture",
  "🍎": "red apple pomme rouge fruit food nourriture",
  "🍐": "pear poire fruit food nourriture",
  "🍊": "tangerine mandarine orange fruit food nourriture",
  "🍋": "lemon citron fruit food nourriture sour acide",
  "🍌": "banana banane fruit food nourriture",
  "🍇": "grapes raisins fruit food nourriture wine vin",
  "🫐": "blueberries myrtilles fruit food nourriture berry baie",
  "🍈": "melon fruit food nourriture",
  "🍑": "peach peche fruit food nourriture",
  "🥭": "mango mangue fruit food nourriture",
  "🍍": "pineapple ananas fruit food nourriture tropical",
  "🥥": "coconut noix de coco fruit food nourriture tropical",
  "🥝": "kiwi fruit food nourriture",
  "🍅": "tomato tomate vegetable legume food nourriture",
  "🍆": "eggplant aubergine vegetable legume food nourriture",
  "🥑": "avocado avocat fruit food nourriture",
  "🥦": "broccoli brocoli vegetable legume food nourriture",
  "🥬": "leafy green feuille verte salad salade vegetable legume",
  "🥒": "cucumber concombre vegetable legume food nourriture",
  "🌶️": "hot pepper piment spicy epice hot chaud",
  "🌽": "ear of corn mais vegetable legume food nourriture",
  "🥕": "carrot carotte vegetable legume food nourriture",
  "🧄": "garlic ail food nourriture",
  "🧅": "onion oignon vegetable legume food nourriture",
  "🥔": "potato pomme de terre vegetable legume food nourriture",
  "🍠": "roasted sweet potato patate douce food nourriture",
  "🥐": "croissant bread pain food nourriture french francais",
  "🥯": "bagel bread pain food nourriture",
  "🍞": "bread pain food nourriture",
  "🥖": "baguette bread pain food nourriture french francais",
  "🥨": "pretzel bretzel food nourriture",
  "🧀": "cheese wedge fromage food nourriture",
  "🥚": "egg oeuf food nourriture",
  "🍳": "cooking oeuf au plat breakfast petit dejeuner food nourriture",
  "🥞": "pancakes crepes breakfast petit dejeuner food nourriture",
  "🧇": "waffle gaufre breakfast petit dejeuner food nourriture",
  "🥓": "bacon food nourriture meat viande",
  "🍔": "hamburger burger food nourriture fast food",
  "🍟": "french fries frites food nourriture",
  "🍕": "pizza food nourriture italian italien",
  "🌭": "hot dog hotdog food nourriture",
  "🥪": "sandwich food nourriture",
  "🌮": "taco mexican mexicain food nourriture",
  "🌯": "burrito wrap mexican mexicain food nourriture",
  "🥗": "green salad salade healthy healthy food nourriture",
  "🥘": "shallow pan of food paella casserole food nourriture",
  "🍝": "spaghetti pasta pates italian italien food nourriture",
  "🍜": "steaming bowl ramen nouilles soup soupe asian asiatique food nourriture",
  "🍲": "pot of food potage stew ragoût soup soupe food nourriture",
  "🍛": "curry rice riz curry indian indien food nourriture",
  "🍣": "sushi japanese japonais food nourriture fish poisson",
  "🍱": "bento box japanese japonais food nourriture",
  "🥟": "dumpling ravioli ravioli asian asiatique food nourriture",
  "🍤": "fried shrimp crevette panee food nourriture",
  "🍙": "rice ball onigiri riz japanese japonais food nourriture",
  "🍚": "cooked rice riz food nourriture",
  "🍥": "fish cake with swirl kamaboko japanese japonais food nourriture",
  "🥠": "fortune cookie biscuit chinois chinese food nourriture",
  "🍢": "oden japanese japonais food nourriture skewer brochette",
  "🍡": "dango japanese japonais sweet sucre food nourriture",
  "🍧": "shaved ice granita glace dessert food nourriture",
  "🍨": "ice cream glace dessert food nourriture",
  "🥧": "pie tarte dessert food nourriture",
  "🍰": "shortcake gateau slice part dessert food nourriture",
  "🍮": "custard flan creme dessert food nourriture",
  "🍭": "lollipop sucette candy bonbon sweet sucre",
  "🍬": "candy bonbon sweet sucre",
  "🍫": "chocolate bar chocolat sweet sucre food nourriture",
  "🍿": "popcorn pop corn cinema movie film food nourriture",
  "🍪": "cookie biscuit sweet sucre food nourriture",
  "🌰": "chestnut chataigne food nourriture",
  "🥜": "peanuts cacahuetes nuts noix food nourriture",
  "🍯": "honey pot pot de miel honey bee abeille sweet sucre",
  "🥛": "glass of milk verre de lait drink boisson",
  "🍼": "baby bottle biberon baby bebe milk lait",
  "☕": "hot beverage cafe coffee tea the drink boisson hot chaud",
  "🍵": "teacup without handle the tea drink boisson",
  "🧃": "beverage box jus juice drink boisson box briquette",
  "🥤": "cup with straw soda drink boisson smoothie",
  "🧊": "ice cube glacon cold froid ice",
  "🍽️": "fork and knife with plate assiette couverts dinner diner food nourriture",
  "🥄": "spoon cuillere utensil couvert",
  "⚽": "soccer ball football soccer sport ball ballon",
  "🏀": "basketball sport ball ballon",
  "🏈": "american football football americain sport ball ballon",
  "⚾": "baseball sport ball ballon",
  "🥎": "softball sport ball ballon",
  "🎾": "tennis sport ball ballon racket raquette",
  "🏐": "volleyball sport ball ballon",
  "🏉": "rugby football sport ball ballon",
  "🥏": "flying disc frisbee sport",
  "🎱": "pool 8 ball billard sport game jeu",
  "🪀": "yo-yo yoyo toy jouet",
  "🏓": "ping pong table tennis tennis de table sport",
  "🏸": "badminton sport racket raquette",
  "🏒": "ice hockey hockey sur glace sport",
  "🏑": "field hockey hockey sur gazon sport",
  "🥍": "lacrosse sport",
  "🏏": "cricket sport",
  "🥅": "goal net but cage sport",
  "⛳": "flag in hole golf sport",
  "🪁": "kite cerf-volant fly voler wind vent",
  "🎣": "fishing pole peche fish poisson sport",
  "🤿": "diving mask plongee snorkel scuba sea mer",
  "🎽": "running shirt maillot running sport",
  "🎿": "skis ski snow neige winter hiver sport",
  "🛷": "sled luge snow neige winter hiver",
  "🥌": "curling stone curling sport",
  "🎯": "direct hit cible dart flechette bullseye target",
  "🪃": "boomerang australia australie",
  "🎮": "video game jeu video controller manette gaming",
  "🕹️": "joystick jeu video gaming arcade",
  "🎰": "slot machine casino game jeu gambling",
  "🎲": "game die de dice game jeu",
  "🧩": "puzzle piece puzzle game jeu",
  "🎨": "artist palette palette art paint peinture creative",
  "🎭": "performing arts theatre theater comedy comedie masks masques",
  "🎪": "circus tent chapiteau circus cirque party fete",
  "🎟️": "admission tickets billets ticket entry entree",
  "🎫": "ticket billet entry entree",
  "🎖️": "military medal medaille militaire award recompense",
  "🏆": "trophy trophee winner gagnant champion award",
  "🏅": "sports medal medaille sport award",
  "🥇": "1st place medal medaille or gold premier first",
  "🥈": "2nd place medal medaille argent silver deuxieme",
  "🥉": "3rd place medal medaille bronze third troisieme",
  "🎗️": "reminder ribbon ruban souvenir awareness",
  "🎼": "musical score partition music musique",
  "🎶": "musical notes notes musique music",
  "🎤": "microphone micro karaoke sing chanter music musique",
  "🎧": "headphone casque music musique listen ecouter",
  "📻": "radio music musique",
  "🎷": "saxophone saxo music musique jazz",
  "🪗": "accordion accordion accordion music musique",
  "🎸": "guitar guitare music musique rock",
  "🎹": "musical keyboard piano music musique",
  "🎺": "trumpet trompette music musique",
  "🎻": "violin violon music musique",
  "🪕": "banjo music musique",
  "🥁": "drum batterie music musique",
  "🎬": "clapper board clap cinema movie film",
  "🎉": "party popper confettis celebration party fete yay",
  "🎊": "confetti ball confettis celebration party fete",
  "🎁": "wrapped gift cadeau present birthday anniversaire",
  "🎃": "jack-o-lantern citrouille halloween",
  "🧨": "firecracker petard firework feu dartifice",
  "🪅": "pinata party fete mexican mexicain celebration",
  "🚗": "automobile car voiture vehicle vehicule",
  "🚕": "taxi car voiture vehicle vehicule",
  "🚙": "sport utility vehicle suv car voiture",
  "🚌": "bus vehicle vehicule",
  "🚎": "trolleybus bus vehicle vehicule",
  "🏎️": "racing car voiture de course race racing sport",
  "🚓": "police car voiture de police police",
  "🚑": "ambulance emergency urgence hospital hopital",
  "🚒": "fire engine camion de pompiers fire feu",
  "🚐": "minibus van vehicle vehicule",
  "🚚": "delivery truck camion delivery livraison",
  "🚛": "articulated lorry semi truck camion",
  "🚜": "tractor tracteur farm ferme",
  "🛴": "kick scooter trottinette",
  "🚲": "bicycle velo bike cycling cyclisme sport",
  "🛵": "motor scooter scooter vespa",
  "🏍️": "motorcycle moto racing",
  "🚨": "police car light gyrophare siren alert alerte",
  "🚡": "aerial tramway telepherique mountain montagne",
  "🚠": "mountain cableway telecabine mountain montagne",
  "🚃": "railway car wagon train",
  "🚋": "tram car tramway",
  "🚞": "mountain railway train montagne",
  "🚝": "monorail train",
  "🚄": "high-speed train tgv train rapide",
  "🚅": "bullet train shinkansen train rapide",
  "🚈": "light rail train leger",
  "🚂": "locomotive train steam vapeur",
  "🚆": "train",
  "🚇": "metro subway underground",
  "🚊": "tram tramway",
  "🚉": "station gare train",
  "✈️": "airplane avion flight vol travel voyage plane",
  "🛫": "airplane departure depart avion takeoff decollage",
  "🛬": "airplane arrival arrivee avion landing atterrissage",
  "🛩️": "small airplane petit avion plane",
  "💺": "seat siege airplane avion",
  "🚀": "rocket fusee space espace launch lancement",
  "🛸": "flying saucer ovni ufo alien space espace",
  "🚁": "helicopter helicoptere",
  "🛶": "canoe boat bateau water eau",
  "⛵": "sailboat voilier boat bateau sailing",
  "🚤": "speedboat hors-bord boat bateau",
  "🛥️": "motor boat bateau a moteur",
  "🛳️": "passenger ship paquebot cruise croisiere",
  "⛴️": "ferry boat bateau",
  "🚢": "ship bateau boat sea mer",
  "⚓": "anchor ancre boat bateau sea mer",
  "⛽": "fuel pump pompe essence gas station station service",
  "🚧": "construction barrier travaux road route warning attention",
  "🗺️": "world map carte monde travel voyage",
  "🗿": "moai statue ile de paques easter island",
  "🗽": "statue of liberty statue de la liberte new york usa",
  "🗼": "tokyo tower tour tokyo japan japon",
  "🏰": "castle chateau european europeen fairy tale conte",
  "🏯": "japanese castle chateau japonais japan japon",
  "🎡": "ferris wheel grande roue amusement park parc attractions",
  "🎢": "roller coaster montagnes russes amusement park",
  "🎠": "carousel horse manege horse cheval",
  "⛲": "fountain fontaine water eau park parc",
  "⛱️": "umbrella on ground parasol beach plage sun soleil",
  "🏖️": "beach with umbrella plage beach vacation vacances",
  "🏝️": "desert island ile desert tropical vacation vacances",
  "🏜️": "desert desert sand sable hot chaud",
  "🌋": "volcano volcan lava lave mountain montagne",
  "⛰️": "mountain montagne nature",
  "🏔️": "snow-capped mountain montagne enneigee snow neige",
  "🗻": "mount fuji mont fuji japan japon",
  "🏕️": "camping tent tente nature outdoors",
  "⛺": "tent tente camping",
  "🏠": "house maison home domicile",
  "🏡": "house with garden maison jardin home",
  "🏘️": "houses maisons neighborhood quartier",
  "🏗️": "building construction chantier crane grue",
  "🏭": "factory usine industry industrie",
  "🏢": "office building immeuble bureau building",
  "🏬": "department store grand magasin shopping",
  "🏥": "hospital hopital doctor medecin health sante",
  "🏦": "bank banque money argent",
  "🏨": "hotel travel voyage sleep dormir",
  "🏪": "convenience store epicerie shop magasin",
  "🏫": "school ecole education",
  "💒": "wedding chapel mariage love amour church eglise",
  "🏛️": "classical building bâtiment classique museum musee",
  "⛪": "church eglise christian chretien religion",
  "🕌": "mosque mosquee islam religion",
  "🕍": "synagogue judaism judaisme religion",
  "🛕": "hindu temple temple hindou religion",
  "⛩️": "shinto shrine sanctuaire shinto japan japon",
  "🌁": "foggy brumeux fog brouillard",
  "🌃": "night with stars nuit etoiles city ville night",
  "🏙️": "cityscape paysage urbain city ville skyline",
  "🌄": "sunrise over mountains lever de soleil montagnes morning matin",
  "🌅": "sunrise lever de soleil morning matin beach plage",
  "🌆": "cityscape at dusk ville crepuscule evening soir",
  "🌇": "sunset coucher de soleil evening soir",
  "🌉": "bridge at night pont nuit",
  "🎆": "fireworks feux dartifice celebration party fete",
  "🎇": "sparkler cierge magique fireworks celebration",
  "🌌": "milky way voie lactee stars etoiles space espace night nuit",
  "🗾": "map of japan carte du japon japan",
  "⌚": "watch montre time temps clock horloge",
  "📱": "mobile phone telephone portable smartphone phone",
  "💻": "laptop computer ordinateur portable computer pc",
  "⌨️": "keyboard clavier computer ordinateur",
  "🖥️": "desktop computer ordinateur de bureau computer pc",
  "🖨️": "printer imprimante print imprimer",
  "🖱️": "computer mouse souris computer",
  "💽": "computer disk disque minidisc",
  "💾": "floppy disk disquette save sauvegarder",
  "💿": "optical disk cd disc",
  "📀": "dvd disc",
  "📸": "camera with flash appareil photo flash photography",
  "📹": "video camera camera video film",
  "🎥": "movie camera camera cinema film movie",
  "📽️": "film projector projecteur cinema movie film",
  "📞": "telephone receiver combiné phone telephone call appel",
  "☎️": "telephone telephone phone call appel",
  "📟": "pager bip",
  "📠": "fax machine fax",
  "📺": "television tv tele",
  "📼": "videocassette vhs cassette video",
  "🔍": "magnifying glass tilted left loupe search recherche",
  "🔎": "magnifying glass tilted right loupe search recherche",
  "🕯️": "candle bougie light lumiere",
  "💡": "light bulb ampoule idea idee light lumiere",
  "🔦": "flashlight lampe torche light lumiere",
  "🏮": "red paper lantern lanterne japonaise japan",
  "📔": "notebook with decorative cover carnet notebook",
  "📕": "closed book livre ferme book red rouge",
  "📖": "open book livre ouvert read lire",
  "📗": "green book livre vert book",
  "📘": "blue book livre bleu book",
  "📙": "orange book livre orange book",
  "📚": "books livres stack pile read lire",
  "📓": "notebook carnet",
  "📒": "ledger registre notebook",
  "📜": "scroll parchemin document",
  "📄": "page facing up page document",
  "📰": "newspaper journal news actualites",
  "🔖": "bookmark marque-page",
  "🏷️": "label etiquette tag",
  "💰": "money bag sac dargent money argent rich riche",
  "💵": "dollar banknote billet dollar money argent",
  "💳": "credit card carte bancaire money argent payment paiement",
  "✉️": "envelope enveloppe mail email letter lettre",
  "📧": "e-mail email mail letter lettre",
  "📩": "envelope with arrow enveloppe mail",
  "📤": "outbox tray boite denvoi send envoyer",
  "📥": "inbox tray boite de reception receive recevoir",
  "📦": "package colis box boite delivery livraison",
  "📫": "closed mailbox with raised flag boite aux lettres mail",
  "📮": "postbox boite postale mail letter lettre",
  "✏️": "pencil crayon write ecrire",
  "✒️": "black nib plume pen stylo write ecrire",
  "🖋️": "fountain pen stylo plume write ecrire",
  "🖊️": "pen stylo write ecrire",
  "🖌️": "paintbrush pinceau art paint peinture",
  "🖍️": "crayon pastel art draw dessiner",
  "📝": "memo note write ecrire",
  "💼": "briefcase mallette business travail work",
  "📁": "file folder dossier file",
  "📂": "open file folder dossier ouvert",
  "📅": "calendar calendrier date",
  "📆": "tear-off calendar calendrier date",
  "📈": "chart increasing graphique hausse growth croissance",
  "📉": "chart decreasing graphique baisse decline",
  "📊": "bar chart diagramme barres stats",
  "📋": "clipboard presse-papiers checklist",
  "📌": "pushpin punaise pin",
  "📍": "round pushpin epingle location lieu map carte",
  "📎": "paperclip trombone clip",
  "📏": "straight ruler regle measure mesurer",
  "📐": "triangular ruler equerre measure mesurer",
  "✂️": "scissors ciseaux cut couper",
  "🔒": "locked cadenas locked securite security",
  "🔓": "unlocked cadenas ouvert unlock",
  "🔑": "key cle unlock password mot de passe",
  "🗝️": "old key vieille cle key",
  "🔨": "hammer marteau tool outil",
  "🔧": "wrench cle a molette tool outil fix reparer",
  "🔩": "nut and bolt ecrou boulon tool outil",
  "⚙️": "gear engrenage settings reglages settings",
  "🧲": "magnet aimant",
  "🔗": "link lien chain chaine",
  "⛓️": "chains chaines",
  "🧪": "test tube tube a essai science lab laboratoire",
  "🧫": "petri dish boite de petri bacteria bacterie science microbe",
  "🧬": "dna adn genetics genetique science",
  "🔬": "microscope science lab laboratoire",
  "🔭": "telescope telescope space espace stars etoiles",
  "📡": "satellite antenna antenne satellite signal",
  "💉": "syringe seringue vaccine vaccin medicine medecine",
  "💊": "pill comprime medicine medecine drug medicament",
  "🩹": "adhesive bandage pansement bandage hurt blesse",
  "🩺": "stethoscope stethoscope doctor medecin health sante",
  "🚪": "door porte",
  "🪑": "chair chaise seat siege",
  "🚿": "shower douche water eau bathroom salle de bain",
  "🛁": "bathtub baignoire bath bain",
  "🧴": "lotion bottle lotion bottle flacon",
  "🧷": "safety pin epingle a nourrice",
  "🧹": "broom balai clean nettoyer",
  "🧺": "basket panier laundry linge",
  "🧻": "roll of paper papier toilette toilet",
  "🧼": "soap savon clean nettoyer wash laver",
  "🧽": "sponge eponge clean nettoyer",
  "🛒": "shopping cart caddie chariot shopping courses",
  "🪥": "toothbrush brosse a dents teeth dents",
  "🧸": "teddy bear ours en peluche toy jouet cute mignon",
  "🕶️": "sunglasses lunettes de soleil cool",
  "👓": "glasses lunettes eyes yeux",
  "👕": "t-shirt tee shirt clothes vetement",
  "👗": "dress robe clothes vetement",
  "👚": "womans clothes blouse clothes vetement",
  "👖": "jeans pantalon pants clothes vetement",
  "🧣": "scarf echarpe cold froid winter hiver",
  "🧤": "gloves gants cold froid winter hiver",
  "🧥": "coat manteau jacket veste cold froid",
  "🧦": "socks chaussettes clothes vetement",
  "👛": "purse porte-monnaie bag sac money argent",
  "👜": "handbag sac a main bag",
  "🎒": "backpack sac a dos school ecole bag",
  "💎": "gem stone diamant jewel bijou diamond gem",
  "👞": "mans shoe chaussure shoe",
  "👟": "running shoe basket sneakers sport shoe",
  "🩰": "ballet shoes chaussons de danse dance danse",
  "👠": "high-heeled shoe talon aiguille shoe heels",
  "🥾": "hiking boot botte de randonnee boot hiking",
  "🧢": "billed cap casquette hat chapeau",
  "🎩": "top hat haut de forme hat chapeau fancy chic",
  "🎓": "graduation cap toque diplome graduation school ecole",
  "❤️": "red heart coeur rouge love amour",
  "🧡": "orange heart coeur orange love amour",
  "💛": "yellow heart coeur jaune love amour",
  "💚": "green heart coeur vert love amour",
  "💙": "blue heart coeur bleu love amour",
  "🖤": "black heart coeur noir love amour",
  "🤍": "white heart coeur blanc love amour",
  "🤎": "brown heart coeur marron love amour",
  "💔": "broken heart coeur brise heartbroken sad triste",
  "❣️": "heart exclamation coeur exclamation love amour",
  "💕": "two hearts deux coeurs love amour",
  "💓": "beating heart coeur battant love amour",
  "💘": "heart with arrow coeur fleche cupidon love amour",
  "💝": "heart with ribbon coeur ruban gift cadeau love amour",
  "💟": "heart decoration decoration coeur love amour",
  "♈": "aries belier zodiac zodiaque",
  "♉": "taurus taureau zodiac zodiaque",
  "♊": "gemini gemeaux zodiac zodiaque",
  "♋": "cancer zodiac zodiaque",
  "♌": "leo lion zodiac zodiaque",
  "♍": "virgo vierge zodiac zodiaque",
  "♎": "libra balance zodiac zodiaque",
  "♏": "scorpio scorpion zodiac zodiaque",
  "♐": "sagittarius sagittaire zodiac zodiaque",
  "♑": "capricorn capricorne zodiac zodiaque",
  "♒": "aquarius verseau zodiac zodiaque",
  "♓": "pisces poissons zodiac zodiaque",
  "✔️": "check mark coche check ok yes oui",
  "✅": "check mark button bouton coche check ok yes oui",
  "❌": "cross mark croix x no non cancel annuler",
  "❎": "cross mark button bouton croix x no non",
  "➕": "plus plus add ajouter",
  "➖": "minus moins subtract soustraire",
  "➗": "divide division",
  "✖️": "multiply multiplication fois x",
  "♾️": "infinity infini forever toujours",
  "‼️": "double exclamation double exclamation bang",
  "⁉️": "exclamation question interrobang",
  "❓": "red question mark point dinterrogation question",
  "❔": "white question mark point dinterrogation question",
  "❕": "white exclamation mark point dexclamation",
  "❗": "red exclamation mark point dexclamation bang",
  "〰️": "wavy dash vague tilde",
  "💯": "hundred points cent points perfect parfait score",
  "⚠️": "warning attention danger caution",
  "🚫": "prohibited interdit ban no non stop",
  "⛔": "no entry entree interdite stop",
  "♻️": "recycling symbol recyclage recycle green vert",
  "🔱": "trident emblem trident poseidon",
  "🔰": "japanese symbol for beginner debutant japan",
  "⚜️": "fleur-de-lis fleur de lys",
  "🔆": "bright button luminosite bright",
  "🔅": "dim button luminosite basse dim",
  "✳️": "eight-spoked asterisk asterisque",
  "❇️": "sparkle etincelle",
  "🌐": "globe with meridians globe internet web world monde",
  "⬆️": "up arrow fleche haut up",
  "↗️": "up-right arrow fleche haut droite",
  "➡️": "right arrow fleche droite right",
  "↘️": "down-right arrow fleche bas droite",
  "⬇️": "down arrow fleche bas down",
  "↙️": "down-left arrow fleche bas gauche",
  "⬅️": "left arrow fleche gauche left",
  "↖️": "up-left arrow fleche haut gauche",
  "↕️": "up-down arrow fleche haut bas",
  "↔️": "left-right arrow fleche gauche droite",
  "↩️": "right arrow curving left retour",
  "↪️": "left arrow curving right avancer",
  "🔃": "clockwise vertical arrows rafraichir refresh reload",
  "🔄": "counterclockwise arrows button refresh reload rafraichir",
  "🔔": "bell cloche notification alert alerte",
  "🚩": "triangular flag drapeau rouge red flag",
  "🏁": "chequered flag drapeau a damier finish fin race",
  "🎌": "crossed flags drapeaux croises japan japon",
  "🔴": "red circle cercle rouge red color couleur",
  "🟠": "orange circle cercle orange color couleur",
  "🟡": "yellow circle cercle jaune yellow color couleur",
  "🟢": "green circle cercle vert green color couleur",
  "🔵": "blue circle cercle bleu blue color couleur",
  "🟣": "purple circle cercle violet purple color couleur",
  "🟤": "brown circle cercle marron brown color couleur",
  "⚫": "black circle cercle noir black color couleur",
  "⚪": "white circle cercle blanc white color couleur",
  "🟥": "red square carre rouge red color couleur",
  "🟧": "orange square carre orange color couleur",
  "🟨": "yellow square carre jaune yellow color couleur",
  "🟩": "green square carre vert green color couleur",
  "🟦": "blue square carre bleu blue color couleur",
  "🟪": "purple square carre violet purple color couleur",
  "⬛": "black large square grand carre noir",
  "⬜": "white large square grand carre blanc",
  "🔶": "large orange diamond losange orange",
  "🔷": "large blue diamond losange bleu",
  "🔸": "small orange diamond petit losange orange",
  "🔹": "small blue diamond petit losange bleu",
  "🔺": "red triangle pointed up triangle rouge haut",
  "🔻": "red triangle pointed down triangle rouge bas",
  "💠": "diamond with a dot losange point",
  "🔘": "radio button bouton radio",
};

const _searchIndex = new Map();
for (const [emoji, tags] of Object.entries(EMOJI_TAGS)) {
  const hay = `${emoji} ${tags}`.toLowerCase().normalize("NFD").replace(/\p{M}/gu, "");
  _searchIndex.set(emoji, hay.split(/\s+/).filter(Boolean));
}

function normalizeQuery(q) {
  return String(q || "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{M}/gu, "")
    .trim();
}

/** Un mot de requête matche un tag : égalité, ou préfixe si ≥ 4 caractères. */
function tokenMatches(token, word) {
  if (token === word) return true;
  if (word.length >= 4 && token.startsWith(word)) return true;
  return false;
}

/** Recherche bilingue (EN/FR). Requête vide = pas de filtre texte. */
export function searchEmojis(query, { groupName = null, limit = 200 } = {}) {
  const q = normalizeQuery(query);
  const words = q ? q.split(/\s+/).filter(Boolean) : [];
  const groups = groupName
    ? EMOJI_GROUPS.filter((g) => g.name === groupName)
    : EMOJI_GROUPS;
  const seen = new Set();
  const out = [];
  for (const g of groups) {
    for (const emoji of g.emojis) {
      if (seen.has(emoji)) continue;
      if (words.length) {
        const tokens = _searchIndex.get(emoji) || [];
        if (!words.every((w) => tokens.some((t) => tokenMatches(t, w)))) continue;
      }
      seen.add(emoji);
      out.push(emoji);
      if (out.length >= limit) return out;
    }
  }
  return out;
}

export const EMOJI_COUNT = EMOJI_GROUPS.reduce((n, g) => n + g.emojis.length, 0);
